### ISSUE TITLE
Add return an ackknowledge from IO activation

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/provider_actuators#20]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Enhancement
Add a topic to confirm that the activation of the IO Board has been done.

## Current Behavior
No return is made.

## Possible Solution
Add a publisher with the custom message

## Environment Used
- Project version : 1.2.1
- docker version : 20.10.5
- docker-compose version : 1.28.5

**Comment by Kam0ss** [comment]
This should be a service, not a message, you ask for an IO activation and get the answer with a Bool.

**Comment by supertoto29** [comment]
It won't be possible by the underwater communication to obtain the data from the activation if it's in a service. The purpose of a message is to allow the underwater com node to catch the return from the provider.

**Comment by supertoto29** [comment]
As the underwater communication project has been changed, this issue is no more needed
